version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:  
      - 5432:5432   
    environment:
      - POSTGRES_DB=studioDB
      - POSTGRES_USER=rishi
      - POSTGRES_PASSWORD=Rishi@638963

  adminer:    
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: ./studio_backend
    command: sh -c "./wait_for_db.sh db python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./studio_backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=studioDB
      - POSTGRES_USER=rishi
      - POSTGRES_PASSWORD=Rishi@638963
      - DB_HOST=db
    env_file:
      - .env  
    depends_on:
      - db

  frontend:
    build: ./my-studio-frontend
    volumes:
      - ./my-studio-frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - .env  
    depends_on:
      - web
